**Introduction to NumPy**

NumPy (short form for Numerical Python) is the most fundamental package designed for scientific computing and data analysis. Most of the other packages such as pandas, statsmodels are built on top of it, and is an important package to know and learn about. At the heart of NumPy is a data structure called **ndarray**. ndarray is a basically a multi-dimensional array that is built specifically for the purpose of numerical data analysis. Python also has array capabilities, but they are more generic. The advantage of using ndarray is that processing is extremely efficient and fast. 

You can perform standard mathematical operations on either individual elements or complete array. The range of functions covered is linear algebra, statistical operations, and other specialized mathematical operations. For our purpose, we need to know about ndarray and the range of mathematical functions that are relevant to our research purpose. If you already know languages such as C, Fortran, then you can integrate NumPy code with code written in these languages and can pass NumPy arrays seamlessly. 

From an overall perspective, understanding of NumPy will help us in using pandas effectively as it is built on top of NumPy and frequently we will also be using functions of NumPy in research work. In the current session, we will only look at some of the most important features of NumPy. For a full listing of NumPy features, please visit http://wiki.scipy.org/Numpy_Example_List .

Possible application of NumPy package in research work are:

+ Algorithmic operations such as sorting, grouping and set operations
+ Performing repetitive operations on whole arrays of data without using loops
+ Data merging and alignment operations
+ Data indexing, filtering, and transformation on individual elements or whole arrays
+ Data summarization and descriptive statistics

**Installing NumPy**

In order to check if NumPy is installed, go to Package Manager and type NumPy. You will get a list of packages with names closely matching to NumPy. For our purpose, we need to focus on package named numpy 1.xx. If the package is not installed, click on Install. 

**Importing NumPy**

In order to be able to use NumPy, first import it using import statement

In [1]:
import numpy as np
np?

The above statement will import all of NumPy into your workspace. For starters its good, but if you are doing performance intensive work, then saving space is of importance. In such cases, you can import specific modules of NumPy by using

In [6]:
from numpy import array


In [47]:
import array from numpy
#syntax error

SyntaxError: invalid syntax (<ipython-input-47-be51fbd05c70>, line 1)

In [54]:
import numpy.array 
#it doesnt work

ModuleNotFoundError: No module named 'numpy.array'

ndarray
The most important data structure in NumPy is an n-dimensional array object. Using ndarray, you can store large multidimensional datasets in Python. Being an array, you can perform mathematical operations on these arrays either one element at a time or on complete arrays without using loops. The way to initialize an array object is

In [7]:
a=(1,2,3,4,5)
b=(10,20,30,40,50)
a1= array(a)
b1= array(b)

print(a) 
print(b) 
print(a1)
print(b1)
print(a+b) # concatenates string
print(a1+b1) 
print (a1+5) 
print (a1**2) 

#dict1 = {a:2,3:4}
#a = array(dict1) 
# cant pass a dictionary in array

(1, 2, 3, 4, 5)
(10, 20, 30, 40, 50)
[1 2 3 4 5]
[10 20 30 40 50]
(1, 2, 3, 4, 5, 10, 20, 30, 40, 50)
[11 22 33 44 55]
[ 6  7  8  9 10]
[ 1  4  9 16 25]


In [11]:
c = array(np.arange(1,10,2))   #arange function here works as a sequence or counter
anarray = array(np.arange(1,10,0.6)) 
onemorearray = array(np.linspace(1,10,19)) # this goes till the final digit 
print(c)
print(anarray)
print(onemorearray)

[1 3 5 7 9]
[1.  1.6 2.2 2.8 3.4 4.  4.6 5.2 5.8 6.4 7.  7.6 8.2 8.8 9.4]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


With each ndarray are associated two attributes: shape of the array, and type of the array. The shape of the array tells you about dimensionality of the array (rows and columns), and type of the array tells you about the data type contained in the array.

In [280]:
data = np.array((32,45,123.0,756,23,2123))
print(data.shape)
print(data.dtype)
print(data.size)

(6,)
float64
6


In [12]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(data2)
print(arr2)
print(arr2.shape)
print(arr2.dtype)
print(arr2.size)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
int64
8


In [13]:
data2 = [[1,2,3,4],[5,6,7,8],[3,4]]
arr2 = np.array(data2)
print(data2)
print(arr2)

[[1, 2, 3, 4], [5, 6, 7, 8], [3, 4]]
[list([1, 2, 3, 4]) list([5, 6, 7, 8]) list([3, 4])]


<ipython-input-13-dbf977cd798d>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array(data2)


In [14]:
a = np.zeros(50)
b = a.astype(int)

print(a)
print(b)

# astype?
# insert?
# sort?

# help(print)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
#np.twos(30)
#module 'numpy' has no attribute 'twos'

AttributeError: module 'numpy' has no attribute 'twos'

In [16]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [304]:
np.eye(5) # creates a 5*5 identity matrix. 
np.eye(5).astype(int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [15]:
f=[]
for i in range(0,5,1):
    c=[]
    for j in range(0,5,1):
        if j==i:
            c=c+[1]
        else:
            c=c+[0]
        
    f=f+[c]
    
print(array(f))


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [21]:
np.diag(array([1,3,5,3,4,5]))

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

In [317]:
a= array([1,3,5,3,4,5])

b= np.zeros((6,6))

for i in range(0,len(a),1):
    for j in range(0,len(a),1):
        if i==j:
            b[i,j]=a[i]
            
print(b)

[[1. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 5.]]


In [23]:
np.diag(array([1,3,5,3,4,5,3,6,4,0,85,2,1,4,7,8]))

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

**pandas**

pandas is the primary package for performing data analysis tasks in Python. pandas derives its name from panel data analysis and is the fundamental package that provides relational data structures (think Excel, SQL type) and a host of capabilities to play with those data structures. It is the most widely used package in Python for data analysis tasks, and is very good to work with cross sectional, time series, and panel data analysis. Python sits on top of NumPy and can be used with NumPy arrays and the functions in NumPy. How is pandas suited for a researcher’s needs:

+ Has a tabular data structure that can hold both homogenous and heterogenous data.
+ Very good indexing capabilities that makes data alignment and merging easy.
+ Good time series functionality. No need to use different data structures for time series and cross sectional data. Allows for both ordered and unordered time-series data.
+ A host of statistical functions developed around NumPy and pandas that makes a researcher’s task easy and fast.
+ Programming is lot simpler and faster.
+ Easily handles data manipulation and cleaning.
+ Easy to expand and shorten data sets. Comprehensive merging, joins, and group by functionality to join multiple data sets.

**Installing pandas** 

In order to check if pandas is installed, go to Package Manager and type pandas. By default, pandas already comes installed with a distribution of Canopy. If the package is not installed, click on Install.

**Importing pandas**

In order to be able to use NumPy, first import it using import statement


In [2]:
import pandas as pd #this will import pandas into your workspace

In [25]:
import numpy as np  #we will be using numpy functions so import numpy

**Data Structures in pandas**

There are two basic data structures in pandas: Series and DataFrame

**Series:** It is similar to a NumPy 1-dimensional array. In addition to the values that are specified by the programmer, pandas attaches a label to each of the values. If the labels are not provided by the programmer, then pandas assigns labels ( 0 for first element, 1 for second element and so on). A benefit of assigning labels to data values is that it becomes easier to perform manipulations on the dataset as the whole dataset becomes more of a dictionary where each value is associated with a label. 


In [18]:
series1 = pd.Series([10,20,30,40,50,60])
series1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [88]:
series1 = pd.Series((10,20,30,40,50,60))
series1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [20]:
list(series1.values)


[10, 20, 30, 40, 50, 60]

In [433]:
print(series1.values)

[10 20 30 40 50 60]


In [322]:
series1.index

RangeIndex(start=0, stop=6, step=1)


If you want to specify custom index values rather than the default ones provided, you can do so using the following command

In [22]:
series2 = pd.Series([10,20,30,40,50], index=['one','two','three','four','five'])
series2

one      10
two      20
three    30
four     40
five     50
dtype: int64

The ways of accesing elements in a Series object are similar to what we have seen in NumPy, and you can perform NumPy operations on Series data arrays.

In [30]:
series2[2]

30

In [31]:
series2['three']

30

In [32]:
series2[['one', 'three', 'five']]

one      10
three    30
five     50
dtype: int64

In [436]:
series2[[0,1,3]]

one     10
two     20
four    40
dtype: int64

In [24]:
print(series2[range(0,3,1)])
print(series2[np.arange(0,3,1)])

one      10
two      20
three    30
dtype: int64
one      10
two      20
three    30
dtype: int64


In [327]:
series2 + 4

one      14
two      24
three    34
four     44
five     54
dtype: int64

In [91]:
series2 ** 3

one        1000
two        8000
three     27000
four      64000
five     125000
dtype: int64

In [437]:
series2>30

one      False
two      False
three    False
four      True
five      True
dtype: bool

In [ ]:
series2[series2>30]

In [438]:
np.sqrt(series2)

one      3.162278
two      4.472136
three    5.477226
four     6.324555
five     7.071068
dtype: float64

If you have a dictionary, you can create a Series data structure from that dictionary. Suppose you are interested in EPS values for firms and the values come from different sources and is not clean. In that case you dont have to worry about cleaning and aligning those values. 

In [330]:
years = [90, 91, 92, 93, 94, 95,96]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
print(firm1)

firm2 = pd.Series(f1)
print(firm2)


90     8.0
91     9.0
92     7.0
93     8.0
94     9.0
95    11.0
96     NaN
dtype: float64
90     8
91     9
92     7
93     8
94     9
95    11
dtype: int64


In [102]:
firm2 = pd.Series(f1)
firm2
#key as index and values as values( unless we provide another index as in above code)

90     8
91     9
92     7
93     8
94     9
95    11
dtype: int64

In [439]:
f2 = {90:14,92:9, 93:13, 94:5}
firm3 = pd.Series(f2,index=years)
firm3

90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64

In [440]:
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3

90     NaN
91     NaN
92     NaN
93    10.0
94    12.0
95    13.0
dtype: float64

NaN stands for missing or NA values in pandas. Make use of isnull() function to find out if there are any missing values in the data structure.

In [341]:
print(pd.isnull(firm3))
print(firm3[pd.isnull(firm3)])
print(firm3.dropna())

90     True
91     True
92     True
93    False
94    False
95    False
dtype: bool
90   NaN
91   NaN
92   NaN
dtype: float64
93    10.0
94    12.0
95    13.0
dtype: float64


A key feature of Series data is structures is that you don't have to worry about data alignment. For example, if we have run a word count program on two different files and we have the following data structures

In [441]:
dict1 = {'finance': 10, 'earning': 5, 'debt':8}
dict2 = {'finance' : 8, 'compensation':4, 'earning': 9}
count1 = pd.Series(dict1)
count2 = pd.Series(dict2)
print(count1)
print(count2)
print(count2.index)

finance    10
earning     5
debt        8
dtype: int64
finance         8
compensation    4
earning         9
dtype: int64
Index(['finance', 'compensation', 'earning'], dtype='object')


If we want to calculate the sum of common words in combined files, then we dont have to worry about data alignment. If we want to include all words, then we can take care of NaN values and compute the sum. By default, Series data structure ignores NaN values. NaN values stand for missing data values.

In [345]:
count1+count2
#data alignment happens automatically

compensation     NaN
debt             NaN
earning         14.0
finance         18.0
dtype: float64

**Data Frame**

DataFrame is a tabular data structure in which data is laid out in rows and column format (similar to a CSV and SQL file), but it can also be used for higher dimensional data sets. The DataFrame object can contain homogenous and heterogenous values, and can be thought of as a logical extension of Series data structures. In contrast to Series, where there is one index, a DataFrame object has one index for column and one index for rows. This allows flexibility in accessing and manipulating data.

In [442]:
data = pd.DataFrame({'price':[95, 25, 85, 41, 78],
                     'ticker':['AXP', 'CSCO', 'DIS', 'MSFT', 'WMT'],
                     'company':['American Express', 'Cisco', 'Walt Disney','Microsoft', 'Walmart']})
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft
4     78    WMT           Walmart

In [443]:
data = pd.DataFrame({'price':[95, 25, 85, 41, 78],
                     'ticker':['AXP', 'CSCO', 'DIS', 'MSFT', 'WMT'],
                     'company':['American Express', 'Cisco', 'Walt Disney','Microsoft', 'Walmart']},index=(4,5,6,7,8))
data

price ticker           company
4     95    AXP  American Express
5     25   CSCO             Cisco
6     85    DIS       Walt Disney
7     41   MSFT         Microsoft
8     78    WMT           Walmart

If a column is passed with no values, it will simply have NaN values

In order to access a column, simply mention the column name

In [381]:
a=data[['company','price']]
print(a)
c=data.company
print(c)
b=a[a.price>41]
print(b)

            company  price
4  American Express     95
5             Cisco     25
6       Walt Disney     85
7         Microsoft     41
8           Walmart     78
4    American Express
5               Cisco
6         Walt Disney
7           Microsoft
8             Walmart
Name: company, dtype: object
            company  price
4  American Express     95
6       Walt Disney     85
8           Walmart     78


In [444]:
print(data.company[data.price>25])

print(data['company'][data.price>25])



4    American Express
6         Walt Disney
7           Microsoft
8             Walmart
Name: company, dtype: object
4    American Express
6         Walt Disney
7           Microsoft
8             Walmart
Name: company, dtype: object
4    American Express
6         Walt Disney
7           Microsoft
8             Walmart
Name: company, dtype: object


In [122]:
data.company

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [448]:
#accesing location by index
print(data.iloc[2,:])
#same
print(data.iloc[2,])

#data.iloc[,2]
#invalid syntax

price               85
ticker             DIS
company    Walt Disney
Name: 6, dtype: object
price               85
ticker             DIS
company    Walt Disney
Name: 6, dtype: object


In [449]:
#data.iloc[(1,2),]

In [386]:
#accesing location
print(data.loc[data.ticker=='DIS'])
data.loc[data.ticker=='DIS']

   price ticker      company  Year  Year2
6     85    DIS  Walt Disney  2014   2017


price ticker      company  Year  Year2
6     85    DIS  Walt Disney  2014   2017

In [370]:
data.loc[data.price > 50]

price ticker           company
4     95    AXP  American Express
6     85    DIS       Walt Disney
8     78    WMT           Walmart

In [450]:
data[data.price > 50]

price ticker           company
4     95    AXP  American Express
6     85    DIS       Walt Disney
8     78    WMT           Walmart

In order to add additional columns

In [452]:
data['Year2'] = np.arange(2015,2020,1)
data['Year'] = 2014
data

price ticker           company  (pricesquared, Year)  Year2  Year
4     95    AXP  American Express                   NaN   2015  2014
5     25   CSCO             Cisco                   NaN   2016  2014
6     85    DIS       Walt Disney                   NaN   2017  2014
7     41   MSFT         Microsoft                   NaN   2018  2014
8     78    WMT           Walmart                   NaN   2019  2014

In [458]:
data['pricesquared'] = data.price**2
data

price ticker           company  (pricesquared, Year)  Year2 Year  \
4     95    AXP  American Express                   NaN   2015        
5     25   CSCO             Cisco                   NaN   2016        
6     85    DIS       Walt Disney                   NaN   2017        
7     41   MSFT         Microsoft                   NaN   2018        
8     78    WMT           Walmart                   NaN   2019        

   pricesquared  
4          9025  
5           625  
6          7225  
7          1681  
8          6084

In [459]:
del data['pricesquared']
data

del data[('pricesquared','Year')]

#del data.pricesquared
#doesnt work

In [460]:
data['Year'] =''
data

price ticker           company  Year2 Year
4     95    AXP  American Express   2015     
5     25   CSCO             Cisco   2016     
6     85    DIS       Walt Disney   2017     
7     41   MSFT         Microsoft   2018     
8     78    WMT           Walmart   2019

In [462]:
data[['pricesquared','Year']] = np.NaN
data

price ticker           company  Year2  Year  pricesquared
4     95    AXP  American Express   2015   NaN           NaN
5     25   CSCO             Cisco   2016   NaN           NaN
6     85    DIS       Walt Disney   2017   NaN           NaN
7     41   MSFT         Microsoft   2018   NaN           NaN
8     78    WMT           Walmart   2019   NaN           NaN

In [396]:
data['sequence'] = np.arange(1,6)
data

price ticker           company Year  Year2  (pricesquared, Year)  sequence
4     95    AXP  American Express        2015                   NaN         1
5     25   CSCO             Cisco        2016                   NaN         2
6     85    DIS       Walt Disney        2017                   NaN         3
7     41   MSFT         Microsoft        2018                   NaN         4
8     78    WMT           Walmart        2019                   NaN         5

In [397]:
data.values


array([[95, 'AXP', 'American Express', '', 2015, nan, 1],
       [25, 'CSCO', 'Cisco', '', 2016, nan, 2],
       [85, 'DIS', 'Walt Disney', '', 2017, nan, 3],
       [41, 'MSFT', 'Microsoft', '', 2018, nan, 4],
       [78, 'WMT', 'Walmart', '', 2019, nan, 5]], dtype=object)

In [398]:
data.index

Int64Index([4, 5, 6, 7, 8], dtype='int64')

In [401]:
newdata = data.drop(5)
newdata

price ticker           company Year  Year2  (pricesquared, Year)  sequence
4     95    AXP  American Express        2015                   NaN         1
6     85    DIS       Walt Disney        2017                   NaN         3
7     41   MSFT         Microsoft        2018                   NaN         4
8     78    WMT           Walmart        2019                   NaN         5

In [407]:
newdata2 = data[(data.ticker!='DIS')]
newdata2

price ticker           company Year  Year2  (pricesquared, Year)  sequence
4     95    AXP  American Express        2015                   NaN         1
5     25   CSCO             Cisco        2016                   NaN         2
7     41   MSFT         Microsoft        2018                   NaN         4
8     78    WMT           Walmart        2019                   NaN         5

In [25]:
 
# initialize list of lists
#one way
data = [['tom', 10], ['nick', 15], ['juli', 14]]
 
# Create the pandas DataFrame
df = pd.DataFrame(data, columns = ['Name', 'Age'])
 
# print dataframe.
df

Name  Age
0   tom   10
1  nick   15
2  juli   14

In [6]:
# initialise data of lists.
#2nd way
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
 
# Create DataFrame
df = pd.DataFrame(data,index = [4,5,6,7])
 
# Print the output.
df

Name  Age
4    Tom   20
5   nick   21
6  krish   19
7   jack   18

In [412]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
firm1
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3

print(firm1+firm2+firm3)

#one way
df1 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years)
df1


df1.Firm1 = firm1
df1.Firm2 = firm2
df1.Firm3 = firm3
df1



90     NaN
91     NaN
92     NaN
93    31.0
94    26.0
95     NaN
dtype: float64


Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [463]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1)
firm1
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2)
firm2
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3)
firm3

#2nd way
data={'F1':firm1,'F2':firm2,'F3':firm3}
print(data)

lolo = pd.DataFrame(data=data,index=years)
print(lolo)




{'F1': 90     8
91     9
92     7
93     8
94     9
95    11
dtype: int64, 'F2': 90    14
92     9
93    13
94     5
dtype: int64, 'F3': 93    10
94    12
95    13
dtype: int64}
    F1    F2    F3
90   8  14.0   NaN
91   9   NaN   NaN
92   7   9.0   NaN
93   8  13.0  10.0
94   9   5.0  12.0
95  11   NaN  13.0


In [428]:
dft = df1.T
dft

# del dft[91]
# dft

# df1 = dft.T
# df1

# df1.drop('Firm1')
# df1


92    93    94    95
Firm1  7.0   8.0   9.0  11.0
Firm2  9.0  13.0   5.0   NaN
Firm3  NaN  10.0  12.0  13.0

You can pass a number of data structures to DataFrame such as a ndarray, lists, dict, Series, and another DataFrame. You can also reindex to confirm to data to a new index. Reindexing is a powerful feature that allows you to access data in a number of different ways, and also to confirm data to some new time series or other index.

In [464]:
df1

Firm1  Firm2  Firm3
92    7.0    9.0    NaN
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    NaN   13.0

In [430]:
reindexdf1 = df1.reindex([88,89,90,91,92,93,94,95,96,97,98])
reindexdf1

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    NaN    NaN    NaN
91    NaN    NaN    NaN
92    7.0    9.0    NaN
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    NaN   13.0
96    NaN    NaN    NaN
97    NaN    NaN    NaN
98    NaN    NaN    NaN

In [466]:
years1 = [90, 91, 92, 93, 94, 95]
f4 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm4 = pd.Series(f4,index=years)
f5 = {90:14,91:12, 92:9, 93:13, 94:5, 95:8}
firm5 = pd.Series(f5,index=years)
f6 = {90:8, 91: 9, 92:9,93:10, 94:12, 95: 13}
firm6 = pd.Series(f6,index=years)
df2 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years1)
df2.Firm1 = firm4
df2.Firm2 = firm5
df2.Firm3 = firm6
df2


Firm1  Firm2  Firm3
90      8     14      8
91      9     12      9
92      7      9      9
93      8     13     10
94      9      5     12
95     11      8     13

In [166]:
reindexdf2 = df2.reindex([88,89,90,91,92,93,94,95,96,97,98], fill_value=0)
reindexdf2

Firm1  Firm2  Firm3
88      0      0      0
89      0      0      0
90      8     14      8
91      9     12      9
92      7      9      9
93      8     13     10
94      9      5     12
95     11      8     13
96      0      0      0
97      0      0      0
98      0      0      0

Similarly, you have backfill (bfill) method to fill values backwards.

In [ ]:
df2

In [172]:
reindexdf3 = df2.reindex([88,89,90,91,92,93,94,95,96,97,98], method='ffill')
reindexdf3

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    8.0   14.0    8.0
91    9.0   12.0    9.0
92    7.0    9.0    9.0
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    8.0   13.0
96   11.0    8.0   13.0
97   11.0    8.0   13.0
98   11.0    8.0   13.0

In [174]:
reindexdf1

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    NaN    NaN    NaN
91    9.0    NaN    NaN
92    7.0    9.0    NaN
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    NaN   13.0
96    NaN    NaN    NaN
97    NaN    NaN    NaN
98    NaN    NaN    NaN

In [175]:
reindexdf3

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    8.0   14.0    8.0
91    9.0   12.0    9.0
92    7.0    9.0    9.0
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    8.0   13.0
96   11.0    8.0   13.0
97   11.0    8.0   13.0
98   11.0    8.0   13.0

In [467]:
reindexdf1+reindexdf3

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    NaN    NaN    NaN
91    NaN    NaN    NaN
92   14.0   18.0    NaN
93   16.0   26.0   20.0
94   18.0   10.0   24.0
95   22.0    NaN   26.0
96    NaN    NaN    NaN
97    NaN    NaN    NaN
98    NaN    NaN    NaN

In [177]:
reindexdf1.add(reindexdf3, fill_value=0)

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    8.0   14.0    8.0
91   18.0   12.0    9.0
92   14.0   18.0    9.0
93   16.0   26.0   20.0
94   18.0   10.0   24.0
95   22.0    8.0   26.0
96   11.0    8.0   13.0
97   11.0    8.0   13.0
98   11.0    8.0   13.0

In [178]:
reindexdf3.add(reindexdf1, fill_value=0)

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    8.0   14.0    8.0
91   18.0   12.0    9.0
92   14.0   18.0    9.0
93   16.0   26.0   20.0
94   18.0   10.0   24.0
95   22.0    8.0   26.0
96   11.0    8.0   13.0
97   11.0    8.0   13.0
98   11.0    8.0   13.0

In [183]:
np.random.randn(3,3)

array([[-1.28358992,  0.02891623, -1.29486191],
       [ 0.74774704, -0.2438359 , -0.12485772],
       [-1.20117883, -0.00770945, -0.43003488]])

You can use NumPy functions inside DataFrame objects.

In [27]:
dataframe = pd.DataFrame(np.random.randn(3,3),columns=['one','two','three'])
dataframe




one       two     three
0 -0.982098  2.205751 -1.572647
1  2.179274 -0.938029  0.966710
2  1.831092 -1.554346  0.588706

In [28]:
np.abs(dataframe)

one       two     three
0  0.982098  2.205751  1.572647
1  2.179274  0.938029  0.966710
2  1.831092  1.554346  0.588706

In [31]:
dataframe

one       two     three
0 -0.982098  2.205751 -1.572647
1  2.179274 -0.938029  0.966710
2  1.831092 -1.554346  0.588706

In [477]:
f = lambda x:x.max()-x.min()
dataframe.apply(f)
#column is default

one      0.292528
two      1.497548
three    2.321209
dtype: float64

In [474]:
f1 = lambda x: x- np.mean(x)
dataframe.apply(f1)

one       two     three
0 -0.174178  0.565270  0.890208
1  0.118350  0.367008  0.540793
2  0.055828 -0.932278 -1.431001

In [478]:
dataframe.apply(f,axis=1)
#for row calculation

#for column calc use axis=0, though its default

0    0.465365
1    0.586153
2    2.495424
dtype: float64

In [29]:
g = lambda x: x - np.mean(x)
dataframe.apply(g,axis=1)
#again would have column wise

one       two     three
0 -0.865766  2.322082 -1.456316
1  1.443289 -1.674014  0.230726
2  1.542608 -1.842830  0.300222

In [30]:
def f(x):
    return pd.Series([np.mean(x), x.max(), x.min()], index=['mean','max','min'])
dataframe.apply(f,axis=1)

mean       max       min
0 -0.116331  2.205751 -1.572647
1  0.735985  2.179274 -0.938029
2  0.288484  1.831092 -1.554346

In [199]:
def f(x):
    return pd.Series([np.mean(x), x.max(), x.min()], index=['mean','max','min'])
dataframe.apply(f,axis=0)

one       two     three
mean -0.455509 -0.256919  1.013248
max   1.583759  0.862269  3.163648
min  -2.990116 -0.864329 -0.470305

In [45]:
print(dataframe)
print(dataframe[2:].values)
print(dataframe.one)

        one       two     three
0 -0.982098  2.205751 -1.572647
1  2.179274 -0.938029  0.966710
2  1.831092 -1.554346  0.588706
[[ 1.83109166 -1.5543459   0.58870595]]
0   -0.982098
1    2.179274
2    1.831092
Name: one, dtype: float64


In [46]:
def f(x):
    return pd.Series([dataframe[2:].values+ dataframe[2:].values], index=['mean'])
dataframe.apply(f,axis=0)

one  \
mean  [[3.662183312211061, -3.10869180641947, 1.1774...   

                                                    two  \
mean  [[3.662183312211061, -3.10869180641947, 1.1774...   

                                                  three  
mean  [[3.662183312211061, -3.10869180641947, 1.1774...

In [47]:
dataframe = pd.DataFrame(np.random.randn(3,3),columns=['one','two','three'])
dataframe

one       two     three
0  0.572105  0.990698  0.797150
1  0.431575 -2.769210  0.126342
2  0.031333 -0.903677  0.264295

In [48]:
dataframe.sort_values(by='one')

one       two     three
2  0.031333 -0.903677  0.264295
1  0.431575 -2.769210  0.126342
0  0.572105  0.990698  0.797150

In [49]:
dataframe.sort_values(by=['one','two'])

one       two     three
2  0.031333 -0.903677  0.264295
1  0.431575 -2.769210  0.126342
0  0.572105  0.990698  0.797150

In [497]:
dataframe.sum()

one      3.092615
two      2.270367
three    0.066827
dtype: float64

In [498]:
dataframe.sum(axis=1)

0    3.091236
1    2.836088
2   -0.497515
dtype: float64

In [499]:
dataframe.cumsum(axis=1)

one       two     three
0  0.856694  2.178753  3.091236
1  1.149222  2.273019  2.836088
2  1.086699  0.911210 -0.497515

In [206]:
dataframe.describe()

one       two     three
count  3.000000  3.000000  3.000000
mean   0.046099 -1.468927 -0.472319
std    0.831960  0.327557  0.449539
min   -0.510603 -1.828887 -0.953117
25%   -0.432089 -1.609204 -0.677239
50%   -0.353576 -1.389522 -0.401360
75%    0.324450 -1.288948 -0.231920
max    1.002476 -1.188373 -0.062480

In [514]:
variable = dataframe.describe()

#dataframe.get_value(o,'one')

In [515]:
variable['two']

count    3.000000
mean     0.756789
std      0.813439
min     -0.175489
25%      0.474154
50%      1.123797
75%      1.222928
max      1.322059
Name: two, dtype: float64

If you have non-numeric data, then applying describe function would produce statistics such as count, unique, frequency. In addition to this, you can also calculate skewness (skew), kurtosis (kurt), percent changes, difference, and other statistics.

**Missing Data**

pandas have a number of features to deal with missing data. We have seen an example of the case of descriptive statistics, where missing values are not taken into account while calculating the descriptive statistics. Missing data is denoted by NaN. 

In [4]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
firm1
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3
df3 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years)
df3
df3.Firm1 = firm1
df3.Firm2 = firm2
df3.Firm3 = firm3
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [10]:
import numpy as np
df3.fillna(mean())

NameError: name 'mean' is not defined

In [212]:
firm2

90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64

In [517]:
nadeleted = firm2.dropna()
nadeleted

90    14.0
92     9.0
93    13.0
94     5.0
dtype: float64

In [524]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In case of DataFrame, if you use dropna, it deletes entire row by default. Another way is to drop only those rows that are all NA. If you want to drop columns, pass axis=1

In [519]:
cleandf3 = df3.dropna()

In [520]:
cleandf3

Firm1  Firm2  Firm3
93      8   13.0   10.0
94      9    5.0   12.0

In [525]:
clean2 = df3.dropna(how='all')
clean2

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [526]:
columndrop = df3.dropna(axis=1)
columndrop

Firm1
90      8
91      9
92      7
93      8
94      9
95     11

In [223]:
columndrop = df3.dropna(axis=0)
columndrop

Firm1  Firm2  Firm3
93      8   13.0   10.0
94      9    5.0   12.0

In [ ]:
df3

In [527]:
thresholddf = df3.dropna(thresh=2)
thresholddf

Firm1  Firm2  Firm3
90      8   14.0    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [224]:
fillna1 = df3.fillna(5)
fillna1

Firm1  Firm2  Firm3
90      8   14.0    5.0
91      9    5.0    5.0
92      7    9.0    5.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11    5.0   13.0

In [ ]:
df3

In [225]:
fillna2 = df3.fillna({'Firm1':8, 'Firm2': 10, 'Firm3':14})
fillna2

Firm1  Firm2  Firm3
90      8   14.0   14.0
91      9   10.0   14.0
92      7    9.0   14.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11   10.0   13.0

In [226]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [227]:
fillna3 = df3.fillna(method='ffill')
fillna3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9   14.0    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    5.0   13.0

In [228]:
fillna4 = df3.fillna(method='bfill',limit=2)
fillna4

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    9.0   10.0
92      7    9.0   10.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [229]:
fillna5 = df3.fillna(df3.mean())
fillna5
#mean will be column wise

Firm1  Firm2      Firm3
90      8  14.00  11.666667
91      9  10.25  11.666667
92      7   9.00  11.666667
93      8  13.00  10.000000
94      9   5.00  12.000000
95     11  10.25  13.000000

**Hierarchical Indexing**

Hierarchical indexing allows you to have index on an index (multiple index). It is an important feature of pandas using which you can select subsets of data and perform independent analyses on them. For example, suppose you have firm prices data and the data is indexed by firm name. On top of that, you can index firms by industry. Thus, industry becomes an index on top of firms. You can then perform analyses either on individual firm, or on group of firms in an industry, or on the whole dataset.

In [5]:
years = [90,91,92,93,94,95]
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=[90,91,92,93,94,95])
firm2

90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64

In [7]:
import numpy as np

In [51]:
h_i_data = pd.Series(np.random.randn(10),index=[['Ind1','Ind1','Ind1','Ind1','Ind2','Ind2','Ind2','Ind3','Ind3','Ind3'],
                                              [1,2,3,4,1,4,3,1,2,3],['a','b','a','b','a','b','a','b','a','b']])
h_i_data

Ind1  1  a   -0.474764
      2  b    0.511267
      3  a   -1.294952
      4  b   -0.186056
Ind2  1  a   -2.027331
      4  b    0.517326
      3  a   -0.746831
Ind3  1  b    1.013782
      2  a    1.214905
      3  b    0.692945
dtype: float64

In [12]:
h_i_data['Ind3']

1  b   -1.027507
2  a    1.137947
3  b   -1.569646
dtype: float64

In [13]:
h_i_data['Ind1':'Ind3']

Ind1  1  a   -0.717552
      2  b   -1.103509
      3  a   -1.002990
      4  b   -0.921979
Ind2  1  a    2.363415
      4  b    0.222000
      3  a    0.196792
Ind3  1  b   -1.027507
      2  a    1.137947
      3  b   -1.569646
dtype: float64

In [536]:
h_i_data[['Ind1','Ind3']]

Ind1  1  a   -0.031359
      2  b   -1.136411
      3  a    0.398769
      4  b    1.131795
Ind3  1  b    0.051532
      2  a   -0.481243
      3  b    0.282530
dtype: float64

In [50]:
h_i_data[:,3]

NameError: name 'h_i_data' is not defined

In [52]:
h_i_data[:,:,"b"]

Ind1  2    0.511267
      4   -0.186056
Ind2  4    0.517326
Ind3  1    1.013782
      3    0.692945
dtype: float64

In [238]:
h_i_data[:,4]

Ind1    0.706049
dtype: float64

In [537]:
h_i_data['Ind1',3,'a']

0.3987690043398261

In [539]:
h_i_data

Ind1  1  a   -0.031359
      2  b   -1.136411
      3  a    0.398769
      4  b    1.131795
Ind2  1  a    1.175624
      2  b    0.400757
      3  a    0.469878
Ind3  1  b    0.051532
      2  a   -0.481243
      3  b    0.282530
dtype: float64

In [540]:
h_i_data.unstack()

a         b
Ind1 1 -0.031359       NaN
     2       NaN -1.136411
     3  0.398769       NaN
     4       NaN  1.131795
Ind2 1  1.175624       NaN
     2       NaN  0.400757
     3  0.469878       NaN
Ind3 1       NaN  0.051532
     2 -0.481243       NaN
     3       NaN  0.282530

In [541]:
h_i_data.unstack().stack()

Ind1  1  a   -0.031359
      2  b   -1.136411
      3  a    0.398769
      4  b    1.131795
Ind2  1  a    1.175624
      2  b    0.400757
      3  a    0.469878
Ind3  1  b    0.051532
      2  a   -0.481243
      3  b    0.282530
dtype: float64

In [542]:
h_i_data.sum()

2.261873149445889

In [543]:
h_i_data.sum(level=1)

1    1.195798
2   -1.216897
3    1.151177
4    1.131795
dtype: float64

In [544]:
h_i_data.sum(level=0)

Ind1    0.362794
Ind2    2.046259
Ind3   -0.147180
dtype: float64

In [545]:
h_i_data.sum(level=0)

Ind1    0.362794
Ind2    2.046259
Ind3   -0.147180
dtype: float64

In [546]:
h_i_data

Ind1  1  a   -0.031359
      2  b   -1.136411
      3  a    0.398769
      4  b    1.131795
Ind2  1  a    1.175624
      2  b    0.400757
      3  a    0.469878
Ind3  1  b    0.051532
      2  a   -0.481243
      3  b    0.282530
dtype: float64

**IO in pandas**

In this section, we will focus on I/O from text files, csv, excel, and sql files as well as getting data from web such as Yahoo! Finance. Using functions in pandas, you can read data as a DataFrame object. 

**Reading a csv file**

In [245]:
import pandas as pd
import numpy as np

In [547]:
roedatacsv = pd.read_csv('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/roedata.csv')
#roedatacsv
roedatacsv.head(10)

Industry Name  Number of firms     ROE
0           Advertising               65  16.51%
1     Aerospace/Defense               95  21.60%
2         Air Transport               25  42.68%
3               Apparel               70  17.87%
4          Auto & Truck               26  22.05%
5            Auto Parts               75  17.54%
6                  Bank                7  15.03%
7      Banks (Regional)              721   9.52%
8             Beverage                47  27.62%
9  Beverage (Alcoholic)               19  18.28%

If the file does not have a header, then you can either let pandas assign default headers or you can specify custom headers. If you want industry name to be the index of DataFrame, you can achieve that.

In [548]:
roedatacsv = pd.read_csv('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/roedata.csv', index_col = 'Industry Name' )
roedatacsv

Number of firms     ROE
Industry Name                             
Advertising                     65  16.51%
Aerospace/Defense               95  21.60%
Air Transport                   25  42.68%
Apparel                         70  17.87%
Auto & Truck                    26  22.05%
...                            ...     ...
Transportation                  22  14.75%
Trucking                        28  16.01%
Utility (General)               20   7.34%
Utility (Water)                 20   9.95%
Total Market                  7766  15.68%

[97 rows x 2 columns]

In [549]:
roedatacsv = pd.read_csv('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/roedata.csv', usecols = ['Industry Name','ROE'] )
roedatacsv

Industry Name     ROE
0         Advertising  16.51%
1   Aerospace/Defense  21.60%
2       Air Transport  42.68%
3             Apparel  17.87%
4        Auto & Truck  22.05%
..                ...     ...
92     Transportation  14.75%
93           Trucking  16.01%
94  Utility (General)   7.34%
95    Utility (Water)   9.95%
96       Total Market  15.68%

[97 rows x 2 columns]

In [550]:
capm_dem_data = pd.read_table('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/capm_dem.dat', delimiter=' ',header = None)
capm_dem_data

0       1         2         3
0    195710  880211 -0.012605  0.003871
1    195710  880212 -0.008511  0.007406
2    195710  880216  0.008584  0.001411
3    195710  880217 -0.004255  0.002414
4    195710  880218  0.000000  0.002845
..      ...     ...       ...       ...
269  811710  880524  0.024540  0.001700
270  811710  880525  0.008982  0.001598
271  811710  880526  0.000000  0.003151
272  811710  880527  0.002967 -0.000359
273  811710  880531  0.038462  0.006501

[274 rows x 4 columns]

In [551]:
capm_dem_data = pd.read_table('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/capm_dem.dat', delimiter=' ',header = None)
capm_dem_data

0       1         2         3
0    195710  880211 -0.012605  0.003871
1    195710  880212 -0.008511  0.007406
2    195710  880216  0.008584  0.001411
3    195710  880217 -0.004255  0.002414
4    195710  880218  0.000000  0.002845
..      ...     ...       ...       ...
269  811710  880524  0.024540  0.001700
270  811710  880525  0.008982  0.001598
271  811710  880526  0.000000  0.003151
272  811710  880527  0.002967 -0.000359
273  811710  880531  0.038462  0.006501

[274 rows x 4 columns]

In [553]:
# compustatdata = pd.read_csv('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/compustat.csv', index_col = ['ggroup','gvkey'] )
# compustatdata = compustatdata.sort_index(0,ascending=False)
# compustatdata

In [554]:
crsp_data = pd.read_table('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/crsp.output', sep='\s+',header = None)
crsp_data

0         1         2         3       4     5      6      7   \
0    00036110  19840831  19890929  3.311923  22.625  0.97  0.597 -0.172   
1    00036110  19850830  19900928  0.378167  22.625  1.51  0.640 -0.028   
2    00036110  19860829  19910930  0.104652  23.500  1.27  0.446  0.178   
3    00036110  19870831  19920930 -0.391107  37.375  1.50  0.342  0.371   
4    00036110  19880831  19930930 -0.408846  24.625  1.34  0.385  0.286   
..        ...       ...       ...       ...     ...   ...    ...    ...   
686  05652510  19910328  19960430  0.823062  17.875  1.45  0.927  0.125   
687  05654310  19860331  19910430  1.244162  22.750  1.98  0.852  0.031   
688  05654310  19870331  19920430  1.318356  23.125  0.59  0.828 -0.075   
689  05709710  19840330  19890428  0.720602  38.500  3.58  0.556  0.201   
690  05709710  19850329  19900430 -0.628028  30.250  2.54  0.500  0.159   

        8      9      10     11     12       13  
0    0.248  0.153  0.193  0.081  0.163  135.908  
1    0.185  0.149  0.187  0.095  0.148  136.474  
2    0.058  0.157  0.142  0.112  0.129  213.827  
3   -0.097  0.157  0.101  0.122  0.078  392.400  
4   -0.697  0.187  0.044  0.163  0.018  390.429  
..     ...    ...    ...    ...    ...      ...  
686  0.138  0.062  0.044  0.062  0.070   30.388  
687  0.310  0.121  0.066  0.049  0.100   22.614  
688  0.360  0.120  0.080  0.046  0.064   22.986  
689 -0.035  0.203 -0.008  0.201  0.072  238.199  
690 -0.200  0.180 -0.037  0.202  0.000      NaN  

[691 rows x 14 columns]

**Reading Files in Chunks**

When dealing with very large files, sometimes it is handy to work with a subset of file or to work on file iteratively in smaller chunks. This can be done in pandas using chunksize and nrows.

In [255]:
altdata = pd.read_csv('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/abcd.csv', chunksize=1000000 )
altdata

In [257]:
#Try not to run this
altdata1 = pd.read_csv('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/abcd.csv')
altdata1.count()

/Users/vikrantdhawan/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


TICKER         5006178
OFTIC          4985426
CNAME          4985426
ACTDATS        5006178
ESTIMATOR      5006178
FPI            5006178
MEASURE        5006178
VALUE          5006175
FPEDATS        5006178
ACTTIMS        5006178
ANNDATS        5006178
ANNDATS_ACT    3534509
ANNTIMS_ACT    3534509
dtype: int64

Note that in previous case, you did not receive a table as output. Instead you were given an object. This is called a TextParser object. This object allows you to iterate over the complete compustat file according to the chunksize you mentioned. Let us suppose we want to aggregate ebitda values of the entire dataset. 

In [258]:
total = 0
for chunks in altdata:
    total += chunks['ESTIMATOR'].sum()
    print(total)
total

1017039317
2086630305
3124599748
4195450974
5263040616
5267984450


5267984450

** Handling missing values**

Some types of missing values are automatically identified by pandas as NaN while importing the data. Those types are NA, NULL, -1.#IND. Additionally, you can also specify a list of missing values. 

In [263]:
roemissing = pd.read_csv('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/roemissing.csv')
roemissing.head(50)

Industry Name  Number of firms        ROE
0                              Advertising               65     16.51%
1                        Aerospace/Defense               95     21.60%
2                            Air Transport               25     42.68%
3                                  Apparel               70     17.87%
4                             Auto & Truck               26     22.05%
5                               Auto Parts               75     17.54%
6                                     Bank                7     15.03%
7                         Banks (Regional)              721      9.52%
8                                Beverage                47     27.62%
9                     Beverage (Alcoholic)               19     18.28%
10                           Biotechnology              349      6.77%
11                            Broadcasting               30     74.10%
12          Brokerage & Investment Banking               49      9.25%
13                      Building Materials               37      6.78%
14            Business & Consumer Services             -999     12.48%
15                                Cable TV               16     26.62%
16                        Chemical (Basic)               47  10000.00%
17                  Chemical (Diversified)               10    145.00%
18                    Chemical (Specialty)              100     22.10%
19                   Coal & Related Energy               45    -14.66%
20                       Computer Services              129     39.46%
21                       Computer Software              273     21.53%
22                   Computers/Peripherals               66     24.55%
23                            Construction               18      3.62%
24                             Diversified               20     13.06%
25                    Educational Services               40     -0.13%
26                    Electrical Equipment              135     13.67%
27                             Electronics              191      7.98%
28         Electronics (Consumer & Office)               26     25.66%
29                             Engineering               56      7.61%
30                           Entertainment               85     17.45%
31          Environmental & Waste Services              108      8.28%
32                     Farming/Agriculture               29      4.82%
33                         Financial Svcs.               76     15.50%
34  Financial Svcs. (Non-bank & Insurance)               17      6.45%
35                         Food Processing               97     15.94%
36                        Food Wholesalers               18     17.74%
37                   Furn/Home Furnishings               36     12.99%
38                    Healthcare Equipment              193     11.87%
39                   Healthcare Facilities               47     26.29%
40                     Healthcare Products               58      5.52%
41                     Healthcare Services              126     13.14%
42    Heathcare Information and Technology              125      9.45%
43                      Heavy Construction               46     22.00%
44                            Homebuilding               32     32.64%
45                            Hotel/Gaming               89      4.50%
46                      Household Products              139     21.68%
47                    Information Services               71     22.24%
48                     Insurance (General)               26      4.08%
49                        Insurance (Life)               27      6.08%

In [558]:
roemissing = pd.read_csv('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/roemissing.csv', na_values=['NULL',-999] )
roemissing.head(50)

Industry Name  Number of firms        ROE
0                              Advertising             65.0     16.51%
1                        Aerospace/Defense             95.0     21.60%
2                            Air Transport             25.0     42.68%
3                                  Apparel             70.0     17.87%
4                             Auto & Truck             26.0     22.05%
5                               Auto Parts             75.0     17.54%
6                                     Bank              7.0     15.03%
7                         Banks (Regional)            721.0      9.52%
8                                Beverage              47.0     27.62%
9                     Beverage (Alcoholic)             19.0     18.28%
10                           Biotechnology            349.0      6.77%
11                            Broadcasting             30.0     74.10%
12          Brokerage & Investment Banking             49.0      9.25%
13                      Building Materials             37.0      6.78%
14            Business & Consumer Services              NaN     12.48%
15                                Cable TV             16.0     26.62%
16                        Chemical (Basic)             47.0  10000.00%
17                  Chemical (Diversified)             10.0    145.00%
18                    Chemical (Specialty)            100.0     22.10%
19                   Coal & Related Energy             45.0    -14.66%
20                       Computer Services            129.0     39.46%
21                       Computer Software            273.0     21.53%
22                   Computers/Peripherals             66.0     24.55%
23                            Construction             18.0      3.62%
24                             Diversified             20.0     13.06%
25                    Educational Services             40.0     -0.13%
26                    Electrical Equipment            135.0     13.67%
27                             Electronics            191.0      7.98%
28         Electronics (Consumer & Office)             26.0     25.66%
29                             Engineering             56.0      7.61%
30                           Entertainment             85.0     17.45%
31          Environmental & Waste Services            108.0      8.28%
32                     Farming/Agriculture             29.0      4.82%
33                         Financial Svcs.             76.0     15.50%
34  Financial Svcs. (Non-bank & Insurance)             17.0      6.45%
35                         Food Processing             97.0     15.94%
36                        Food Wholesalers             18.0     17.74%
37                   Furn/Home Furnishings             36.0     12.99%
38                    Healthcare Equipment            193.0     11.87%
39                   Healthcare Facilities             47.0     26.29%
40                     Healthcare Products             58.0      5.52%
41                     Healthcare Services            126.0     13.14%
42    Heathcare Information and Technology            125.0      9.45%
43                      Heavy Construction             46.0     22.00%
44                            Homebuilding             32.0     32.64%
45                            Hotel/Gaming             89.0      4.50%
46                      Household Products            139.0     21.68%
47                    Information Services             71.0     22.24%
48                     Insurance (General)             26.0      4.08%
49                        Insurance (Life)             27.0      6.08%

In [562]:
roemissing = pd.read_csv('/Users/vikrantdhawan/Dropbox/My Mac (Vikrant’s MacBook Air)/Downloads/roemissing.csv', na_values={'Number of firms':['NULL',-999],'ROE':['10000.00%']} )
roemissing.head(50)

Industry Name  Number of firms      ROE
0                              Advertising             65.0   16.51%
1                        Aerospace/Defense             95.0   21.60%
2                            Air Transport             25.0   42.68%
3                                  Apparel             70.0   17.87%
4                             Auto & Truck             26.0   22.05%
5                               Auto Parts             75.0   17.54%
6                                     Bank              7.0   15.03%
7                         Banks (Regional)            721.0    9.52%
8                                Beverage              47.0   27.62%
9                     Beverage (Alcoholic)             19.0   18.28%
10                           Biotechnology            349.0    6.77%
11                            Broadcasting             30.0   74.10%
12          Brokerage & Investment Banking             49.0    9.25%
13                      Building Materials             37.0    6.78%
14            Business & Consumer Services              NaN   12.48%
15                                Cable TV             16.0   26.62%
16                        Chemical (Basic)             47.0      NaN
17                  Chemical (Diversified)             10.0  145.00%
18                    Chemical (Specialty)            100.0   22.10%
19                   Coal & Related Energy             45.0  -14.66%
20                       Computer Services            129.0   39.46%
21                       Computer Software            273.0   21.53%
22                   Computers/Peripherals             66.0   24.55%
23                            Construction             18.0    3.62%
24                             Diversified             20.0   13.06%
25                    Educational Services             40.0   -0.13%
26                    Electrical Equipment            135.0   13.67%
27                             Electronics            191.0    7.98%
28         Electronics (Consumer & Office)             26.0   25.66%
29                             Engineering             56.0    7.61%
30                           Entertainment             85.0   17.45%
31          Environmental & Waste Services            108.0    8.28%
32                     Farming/Agriculture             29.0    4.82%
33                         Financial Svcs.             76.0   15.50%
34  Financial Svcs. (Non-bank & Insurance)             17.0    6.45%
35                         Food Processing             97.0   15.94%
36                        Food Wholesalers             18.0   17.74%
37                   Furn/Home Furnishings             36.0   12.99%
38                    Healthcare Equipment            193.0   11.87%
39                   Healthcare Facilities             47.0   26.29%
40                     Healthcare Products             58.0    5.52%
41                     Healthcare Services            126.0   13.14%
42    Heathcare Information and Technology            125.0    9.45%
43                      Heavy Construction             46.0   22.00%
44                            Homebuilding             32.0   32.64%
45                            Hotel/Gaming             89.0    4.50%
46                      Household Products            139.0   21.68%
47                    Information Services             71.0   22.24%
48                     Insurance (General)             26.0    4.08%
49                        Insurance (Life)             27.0    6.08%

**Writing Data**

In [ ]:
roedata = pd.read_csv('/Users/suppi/Documents/ISB/AMPBA/B16/IPD/roedata.csv')
roedata.to_csv('/Users/suppi/Documents/ISB/AMPBA/B16/IPD/roedatawrite.csv')

In [ ]:
roedata = pd.read_csv('/Users/suppi/Documents/ISB/AMPBA/B16/IPD/roedata.csv')
roedata.to_csv('/Users/suppi/Documents/ISB/AMPBA/B16/IPD/roedatawrite2.csv', index=False, columns=['Industry Name','ROE'])

**Merging Data**

In [ ]:
import pandas as pd

In [565]:
left_frame = pd.DataFrame({'key': range(5), 
                           'left_value': ['a', 'b', 'c', 'd', 'e']})
right_frame = pd.DataFrame({'key': range(2, 7), 
                           'right_value': ['f', 'g', 'h', 'i', 'j']})
print(left_frame)
print('\n')
print(right_frame)

   key left_value
0    0          a
1    1          b
2    2          c
3    3          d
4    4          e


   key right_value
0    2           f
1    3           g
2    4           h
3    5           i
4    6           j


In [268]:
pd.merge(left_frame, right_frame, left_on='key', right_on = 'key', how='inner')

key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h

In [270]:
pd.merge(left_frame, right_frame, on='key', how='inner')

key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h

In [271]:
pd.merge(left_frame, right_frame, on='key', how='left')

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           f
3    3          d           g
4    4          e           h

In [272]:
pd.merge(left_frame, right_frame, on='key', how='right')

key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h
3    5        NaN           i
4    6        NaN           j

In [273]:
pd.merge(left_frame, right_frame, on='key', how='outer')

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           f
3    3          d           g
4    4          e           h
5    5        NaN           i
6    6        NaN           j

In [274]:
pd.concat([left_frame, right_frame])

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c         NaN
3    3          d         NaN
4    4          e         NaN
0    2        NaN           f
1    3        NaN           g
2    4        NaN           h
3    5        NaN           i
4    6        NaN           j

In [275]:
pd.concat([left_frame, right_frame], axis=1)

key left_value  key right_value
0    0          a    2           f
1    1          b    3           g
2    2          c    4           h
3    3          d    5           i
4    4          e    6           j